[package]
name = "bao_experiments"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]

[dependencies]
blake2b_simd = { path = "../blake2b_simd" }
blake2s_simd = { path = "../blake2s_simd" }
byteorder = { version = "1.2.4", default-features = false }
rayon = { version = "1.0.2" }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "libtest"

[[bench]]
name = "criterion"
harness = false
